# Generated by Django 2.2.7 on 2019-11-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=100, null=True)),
                ('vehicle_id', models.CharField(max_length=100, null=True)),
                ('alert_type', models.CharField(max_length=100, null=True)),
                ('priority', models.CharField(max_length=100, null=True)),
                ('contact_no', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longtude', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='api1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.CharField(max_length=20, null=True)),
                ('Running', models.CharField(max_length=20, null=True)),
                ('Idle', models.CharField(max_length=20, null=True)),
                ('Stop', models.CharField(max_length=20, null=True)),
                ('NoData', models.CharField(max_length=20, null=True)),
                ('vin', models.CharField(max_length=20, null=True)),
                ('No_of_overspeed', models.CharField(max_length=20, null=True)),
                ('No_of_geofence', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=10, null=True)),
                ('time', models.CharField(max_length=10, null=True)),
                ('startlocation', models.TextField(max_length=100, null=True)),
                ('startodometer', models.FloatField(max_length=10, null=True)),
                ('running', models.CharField(max_length=10, null=True)),
                ('idle', models.CharField(max_length=50, null=True)),
                ('stop', models.CharField(max_length=10, null=True)),
                ('inactive', models.CharField(max_length=10, null=True)),
                ('endodometer', models.FloatField(max_length=10, null=True)),
                ('endlocation', models.CharField(max_length=10, null=True)),
                ('distance', models.FloatField(max_length=10, null=True)),
                ('average', models.IntegerField(null=True)),
                ('current_speed', models.IntegerField(null=True)),
                ('maxstop', models.IntegerField(null=True)),
                ('maxspeed', models.IntegerField(null=True)),
                ('overspeed', models.IntegerField(null=True)),
                ('alert', models.IntegerField(null=True)),
                ('noidle', models.IntegerField(null=True)),
                ('AssetCode', models.CharField(max_length=10, null=True)),
                ('deviceImeiNo', models.CharField(max_length=15, null=True)),
                ('plateNumber', models.CharField(max_length=10, null=True)),
                ('No_of_iterations', models.IntegerField(null=True)),
                ('latitude', models.CharField(max_length=10, null=True)),
                ('longitude', models.CharField(max_length=10, null=True)),
                ('direction', models.CharField(max_length=10, null=True)),
                ('engine_current', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
